#!/usr/bin/env bash
# prints information about the DNS record of a domain

domain () {
	result=$(dig "$fullname" |grep -A1 'ANSWER SECTION:' |tail -n 1 | awk '{ print $0}')
	record=$(echo "$result" | awk '{print $4}')
	ip=$(echo "$result" | awk '{print $5}')
	echo "The subdomain $2 is a record $record and points to $ip"
	}
if (( $# == 1 ))
then
	subdomains=("www" "lb-01" "web-01" "web-02")
	for sub in "${subdomains[@]}"
	do
		result=$(dig "$sub.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $0}')
		record=$(echo "$result" | awk '{print $4}')
		ip=$(echo "$result" | awk '{print $5}')
		echo "The subdomain $sub is a record $record and points to $ip"
	done
elif (( $# == 2 ))
then
	fullname="$2.$1"
	domain "$fullname" "$2"
fi
