#!/usr/bin/env bash
# A script that copies a file from local machine to remote server

path_to_file=$1;
server_ip=$2;
username=$3
path_to_key=$4;
count=$#;

if ((count == 4))
then
	scp -o "StrictHostKeyChecking=no" -i \
		"$path_to_key" "$path_to_file" "$username@$server_ip":~/
fi
