#!/usr/bin/env bash
# redirecting using 301 redirection
# installing Nginx on a remote server

sudo apt-get  update -y
sudo apt-get  install nginx -y
echo "Hello World!"  | sudo tee /var/www/html/index.html
sudo sed -i -e "/server {/a\
       \n\tlocation /redirect_me {\
        \n\treturn 301 https://youtube.com;\
        }"      /etc/nginx/sites-available/default
sudo service nginx restart

