#!/usr/bin/env bash
# A scripts that installs nginx and configures it

# installation
apt-get -y update;
apt-get -y install nginx;

# testing
echo "Hello World!" >> /var/www/html/index.html;

# handling redirection
redirect="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}"
sudo sed -i "53i$redirect" /etc/nginx/sites-available/default

# handling 404 error with a custom page
echo "Ceci n'est pas une page" >> /var/www/html/custom_error.html
error="\\\terror_page 404 /custom_error.html;"
sudo sed -i "45i$error" /etc/nginx/sites-available/default
# restarting nginx 
sudo service nginx restart
