#!/usr/bin/env bash
# configuring a custom header for a server

#installing nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# providing index.html content

echo "Hello World!" | sudo tee /var/www/html/index.html

# configuring custom header
server_name=$(hostname)

custom="\\\n\tlocation / {\n\t\tadd_header X-Served-By $server_name;\n\t}"
sudo sed -i "51i $custom"  /etc/nginx/sites-available/default

# configuring redirection

redirect="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://youtube.com;\n\t}"
sudo sed -i "55i $redirect"  /etc/nginx/sites-available/default
sudo service nginx restart
