#!/usr/bin/env bash
# configuring a HAproxy load balancer

# installing HAproxy for ubuntu 20.4

sudo apt-get update -y
sudo apt-get install haproxy=2.0\* -y

# making a backup copy of config file
cp /etc/haproxy/haproxy.cfg haproxy_backup

# configuring haproxy
echo "
frontend daniel_frontend
	bind 0:80
	mode http
	default_backend daniel_backend
backend daniel_backend
	balance roundrobin
	server 298456-web-01 52.202.61.49:80 check
	server 298456-web-02 100.26.241.214:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee  /etc/default/haproxy
sudo service haproxy restart
