#!/usr/bin/env bash
# ammending the link between symlink and server blocks
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo nginx -s quit
