#!/usr/bin/env bash
# A script that prints fizzbuzz numbers
i=1
while (( i < 101 ))
do
	if (( i % 3 == 0 && i % 5 == 0 ))
	then
	       echo "FizzBuzz"
       elif (( i % 3 == 0 && i % 5 != 0 ))
       then
	     echo "Fizz"
     elif (( i % 3 != 0 && i % 5 == 0 ))
     then
	   echo "Buzz"
   else
	 echo "$i"
	fi
	(( i++ ))
done
