#!/usr/bin/env bash
# A bash script that tells a story about the content of /etc/passwd file
while IFS=":" read -r user_name password user_id gid user_info home shell
do
	echo "The $user_name is part of the $gid gang, lives in $home and 
	rides $shell. $user_id place is protected by the passcode $password, 
	more info about the user here: $user_info"
done < "/etc/passwd"
