#!/usr/bin/env bash
# A script that prints a string using a loop and conditional statement
i=1
while (( i < 11 ))
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
