#!/usr/bin/env bash
# A bash script that uses loop to print time in hours and minutes
i=0
while (( i != 13 ))
do
	echo "Hour: $i"
	j=0
	while (( j < 60 ))
	do
		echo "$j"
		(( j++))
	done
	(( i++ ))
done
