#!/usr/bin/env bash
# configuring nginx to run as nginx user not root
sudo sed -i "5i user nginx;" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo service nginx restart
