#!/usr/bin/env bash
# configuring Nginx to run as non superuser

sudo sed -i 's/^#\suser\s[^;]*;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i '49i \\\n\t listen 8080;\n' /etc/nginx/sites-available/default
sudo service nginx restart
