#!/usr/bin/env bash
# repeating the previous task
sudo sed -i 's/^#\suser\s[^;]*;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo service nginx restart
